/*
 This program was produced and created by three members
    Matthew Byrne
    Cian Larkin 
    Carl Flynn
 */
package WelfareAppFinal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author x17347726
 * @author x17138744
 * @author x17453136
 */

public class WelfareAppGUI extends javax.swing.JFrame  {

    //Delcaration of all data members in Welfare App GUI. The main JFrame for the application.
    private final ArrayList<Welfare> aList;
    private String ppsNo, fname, lname, pAddress, cAddress, contactNum;
    private int count;

    /**
     * Creates new form WelfareAppGUI
     */
    public WelfareAppGUI() {
        initComponents();
        
        //This settings hides the JPanels included at the very start of the application to "false".
        HousingPageMenu.setVisible(false);
        ChildrenPageMenu.setVisible(false);
        PensionPageMenu.setVisible(false);

        /*
        Starting constructor for data members of Welfare that also includes a addtional "count" for a Arraylist
        plus a new instance of "Arraylist<>" called aList.
         */
        
        aList = new ArrayList<>();
        ppsNo = new String();
        fname = new String();
        lname = new String();
        pAddress = new String();
        cAddress = new String();
        contactNum = new String();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelfareAppPageMenu = new javax.swing.JPanel();
        ppsLbl = new javax.swing.JLabel();
        fnameLbl = new javax.swing.JLabel();
        lnameLbl = new javax.swing.JLabel();
        paddressLbl = new javax.swing.JLabel();
        caddressLbl = new javax.swing.JLabel();
        contactNumLbl = new javax.swing.JLabel();
        ppsTb = new javax.swing.JPasswordField();
        fnameTb = new javax.swing.JTextField();
        lnameTb = new javax.swing.JTextField();
        pAddressTb = new javax.swing.JTextField();
        cAddressTb = new javax.swing.JTextField();
        contactNumTb = new javax.swing.JTextField();
        addDetailsBtn = new javax.swing.JButton();
        houseBtn = new javax.swing.JToggleButton();
        childBtn = new javax.swing.JToggleButton();
        pensionBtn = new javax.swing.JToggleButton();
        printActionBtn = new javax.swing.JButton();
        viewBtnMain = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        mainLogo = new javax.swing.JLabel();
        sponsersLogoMain = new javax.swing.JLabel();
        searchDetailsMain = new javax.swing.JButton();
        saveBtnMain = new javax.swing.JButton();
        HomelessLogo = new javax.swing.JLabel();
        ppsCheckBox = new javax.swing.JCheckBox();
        ncirlLogo = new javax.swing.JLabel();
        HousingPageMenu = new javax.swing.JPanel();
        housetypeLbl = new javax.swing.JLabel();
        areaLbl = new javax.swing.JLabel();
        houseComboBox = new javax.swing.JComboBox<>();
        areaComboBox = new javax.swing.JComboBox<>();
        prefernceLbl = new javax.swing.JLabel();
        returnBtnHouse = new javax.swing.JToggleButton();
        preferenceTf = new javax.swing.JTextField();
        clearBtnHouse = new javax.swing.JButton();
        sponsersLogoMain2 = new javax.swing.JLabel();
        socialLogoHouse = new javax.swing.JLabel();
        housingLogo = new javax.swing.JLabel();
        ChildrenPageMenu = new javax.swing.JPanel();
        ReturnBtnChild = new javax.swing.JToggleButton();
        numberLbl = new javax.swing.JLabel();
        orphanLbl = new javax.swing.JLabel();
        disabilityLbl = new javax.swing.JLabel();
        disabilityTf = new javax.swing.JTextField();
        orphanCb = new javax.swing.JComboBox<>();
        nameTf = new javax.swing.JTextField();
        addressLbl = new javax.swing.JLabel();
        addressTf = new javax.swing.JTextField();
        clearBtnChild = new javax.swing.JButton();
        socialLogoChild = new javax.swing.JLabel();
        sponserChildLogo = new javax.swing.JLabel();
        mainChildLogo = new javax.swing.JLabel();
        childrenLogo = new javax.swing.JLabel();
        PensionPageMenu = new javax.swing.JPanel();
        prevemployLbl = new javax.swing.JLabel();
        socialbenefitsLbl = new javax.swing.JLabel();
        disabilitypenLbl = new javax.swing.JLabel();
        prevemployTf = new javax.swing.JTextField();
        socialbenefitsTf = new javax.swing.JTextField();
        disabilitypenTf = new javax.swing.JTextField();
        returnBtnPension = new javax.swing.JToggleButton();
        clearBtnPen = new javax.swing.JButton();
        sponserLogoPen = new javax.swing.JLabel();
        sponsersLogoPen = new javax.swing.JLabel();
        mainLogoPen = new javax.swing.JLabel();
        pensionerLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(700, 400, 400, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("MainJFrame"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());

        WelfareAppPageMenu.setBackground(new java.awt.Color(255, 255, 255));
        WelfareAppPageMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 71, 155), 10));
        WelfareAppPageMenu.setToolTipText("");
        WelfareAppPageMenu.setAutoscrolls(true);
        WelfareAppPageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WelfareAppPageMenu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.setDoubleBuffered(false);
        WelfareAppPageMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        WelfareAppPageMenu.setMaximumSize(new java.awt.Dimension(700, 400));
        WelfareAppPageMenu.setMinimumSize(new java.awt.Dimension(700, 400));
        WelfareAppPageMenu.setName(""); // NOI18N
        WelfareAppPageMenu.setPreferredSize(new java.awt.Dimension(700, 400));
        WelfareAppPageMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppsLbl.setBackground(new java.awt.Color(255, 255, 255));
        ppsLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ppsLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ppsLbl.setText("PPS");
        ppsLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ppsLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ppsLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(ppsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 20));

        fnameLbl.setBackground(new java.awt.Color(255, 255, 255));
        fnameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnameLbl.setText("First Name");
        fnameLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fnameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fnameLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(fnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 20));

        lnameLbl.setBackground(new java.awt.Color(255, 255, 255));
        lnameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLbl.setText("Last Name");
        lnameLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lnameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lnameLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(lnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 20));

        paddressLbl.setBackground(new java.awt.Color(255, 255, 255));
        paddressLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paddressLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paddressLbl.setText("Previous Address");
        paddressLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paddressLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paddressLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(paddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 20));

        caddressLbl.setBackground(new java.awt.Color(255, 255, 255));
        caddressLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        caddressLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        caddressLbl.setText("Current Address");
        caddressLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caddressLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caddressLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(caddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 20));

        contactNumLbl.setBackground(new java.awt.Color(255, 255, 255));
        contactNumLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contactNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactNumLbl.setText("Contact");
        contactNumLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contactNumLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contactNumLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        WelfareAppPageMenu.add(contactNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 20));

        ppsTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ppsTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ppsTb.setMaximumSize(null);
        ppsTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppsTbActionPerformed(evt);
            }
        });
        ppsTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ppsTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(ppsTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 150, 20));

        fnameTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fnameTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fnameTb.setMaximumSize(null);
        fnameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTbActionPerformed(evt);
            }
        });
        fnameTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(fnameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, 20));

        lnameTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lnameTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lnameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTbActionPerformed(evt);
            }
        });
        lnameTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(lnameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, 20));

        pAddressTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pAddressTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddressTbActionPerformed(evt);
            }
        });
        pAddressTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pAddressTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(pAddressTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 180, 20));

        cAddressTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cAddressTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddressTbActionPerformed(evt);
            }
        });
        cAddressTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cAddressTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(cAddressTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 20));

        contactNumTb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        contactNumTb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contactNumTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumTbActionPerformed(evt);
            }
        });
        contactNumTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactNumTbKeyPressed(evt);
            }
        });
        WelfareAppPageMenu.add(contactNumTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, 20));

        addDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        addDetailsBtn.setText("Add");
        addDetailsBtn.setAutoscrolls(true);
        addDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDetailsBtn.setDoubleBuffered(true);
        addDetailsBtn.setFocusPainted(false);
        addDetailsBtn.setSelected(true);
        addDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetailsBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(addDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, 20));

        houseBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        houseBtn.setSelected(true);
        houseBtn.setText("Housing");
        houseBtn.setAutoscrolls(true);
        houseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        houseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        houseBtn.setDoubleBuffered(true);
        houseBtn.setFocusPainted(false);
        houseBtn.setFocusable(false);
        houseBtn.setOpaque(true);
        houseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(houseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 25));

        childBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        childBtn.setSelected(true);
        childBtn.setText("Children");
        childBtn.setAutoscrolls(true);
        childBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        childBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        childBtn.setDoubleBuffered(true);
        childBtn.setFocusPainted(false);
        childBtn.setFocusable(false);
        childBtn.setOpaque(true);
        childBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(childBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 25));

        pensionBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pensionBtn.setSelected(true);
        pensionBtn.setText("O.A.P");
        pensionBtn.setAutoscrolls(true);
        pensionBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pensionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pensionBtn.setDoubleBuffered(true);
        pensionBtn.setFocusPainted(false);
        pensionBtn.setFocusable(false);
        pensionBtn.setOpaque(true);
        pensionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensionBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(pensionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 100, 25));

        printActionBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        printActionBtn.setText("Print");
        printActionBtn.setAutoscrolls(true);
        printActionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printActionBtn.setDoubleBuffered(true);
        printActionBtn.setFocusPainted(false);
        printActionBtn.setSelected(true);
        printActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(printActionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 80, 20));

        viewBtnMain.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        viewBtnMain.setText("Save");
        viewBtnMain.setAutoscrolls(true);
        viewBtnMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBtnMain.setDoubleBuffered(true);
        viewBtnMain.setFocusPainted(false);
        viewBtnMain.setSelected(true);
        viewBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnMainActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(viewBtnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, 20));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setAutoscrolls(true);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setDoubleBuffered(true);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setSelected(true);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 20));

        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/socialprotection.jpg"))); // NOI18N
        WelfareAppPageMenu.add(mainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 90));

        sponsersLogoMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/LogoSponsers.png"))); // NOI18N
        WelfareAppPageMenu.add(sponsersLogoMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 110));

        searchDetailsMain.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        searchDetailsMain.setText("Search");
        searchDetailsMain.setAutoscrolls(true);
        searchDetailsMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDetailsMain.setDoubleBuffered(true);
        searchDetailsMain.setFocusPainted(false);
        searchDetailsMain.setSelected(true);
        searchDetailsMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDetailsMainActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(searchDetailsMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 20));

        saveBtnMain.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        saveBtnMain.setText("View");
        saveBtnMain.setAutoscrolls(true);
        saveBtnMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtnMain.setDoubleBuffered(true);
        saveBtnMain.setFocusPainted(false);
        saveBtnMain.setSelected(true);
        saveBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnMainActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(saveBtnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 80, 20));

        HomelessLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/focuslogo.jpg"))); // NOI18N
        HomelessLogo.setAutoscrolls(true);
        WelfareAppPageMenu.add(HomelessLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 130));

        ppsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppsCheckBoxActionPerformed(evt);
            }
        });
        WelfareAppPageMenu.add(ppsCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        ncirlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/NCIRLLogo.jpeg"))); // NOI18N
        WelfareAppPageMenu.add(ncirlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 160, 110));

        getContentPane().add(WelfareAppPageMenu, "card2");
        WelfareAppPageMenu.getAccessibleContext().setAccessibleName("Welfare App Main Page");
        WelfareAppPageMenu.getAccessibleContext().setAccessibleDescription("Welfare App Main Page");

        HousingPageMenu.setBackground(new java.awt.Color(255, 255, 255));
        HousingPageMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 71, 155), 10));
        HousingPageMenu.setAutoscrolls(true);
        HousingPageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HousingPageMenu.setMaximumSize(new java.awt.Dimension(700, 400));
        HousingPageMenu.setMinimumSize(new java.awt.Dimension(700, 400));
        HousingPageMenu.setPreferredSize(new java.awt.Dimension(700, 400));
        HousingPageMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        housetypeLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        housetypeLbl.setText("House Type");
        housetypeLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HousingPageMenu.add(housetypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, 20));

        areaLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        areaLbl.setText("Area");
        areaLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HousingPageMenu.add(areaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 20));

        houseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bungalo", "Apartment", "Semi-Detached" }));
        houseComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        houseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseComboBoxActionPerformed(evt);
            }
        });
        HousingPageMenu.add(houseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 20));

        areaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dublin 1", "Dublin 2", "Dublin 3", "Dublin 4", "Dublin 5", "Dublin 6", "Dublin 7", "Dublin 8", "Dublin 9", "Dublin 10", "Dublin 11", "Dublin 12", "Dublin 13", "Dublin 14", "Dublin 15", "Dublin 16", "Dublin 17", "Dublin 18", "Dublin 19", "Dublin 20", "Dublin 21", "Dublin 22", "Dublin 23", "Dublin 24" }));
        areaComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        HousingPageMenu.add(areaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 20));

        prefernceLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prefernceLbl.setText("Preference");
        prefernceLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HousingPageMenu.add(prefernceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 100, 20));

        returnBtnHouse.setText("Go Back");
        returnBtnHouse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBtnHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnHouseActionPerformed(evt);
            }
        });
        HousingPageMenu.add(returnBtnHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 100, 20));

        preferenceTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        preferenceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenceTfActionPerformed(evt);
            }
        });
        HousingPageMenu.add(preferenceTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, 20));

        clearBtnHouse.setText("Clear Details");
        clearBtnHouse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBtnHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnHouseActionPerformed(evt);
            }
        });
        HousingPageMenu.add(clearBtnHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, 20));

        sponsersLogoMain2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/LogoSponsers.png"))); // NOI18N
        HousingPageMenu.add(sponsersLogoMain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 110));

        socialLogoHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/socialprotection.jpg"))); // NOI18N
        HousingPageMenu.add(socialLogoHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 90));

        housingLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/houselogo.png"))); // NOI18N
        HousingPageMenu.add(housingLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 260));

        getContentPane().add(HousingPageMenu, "card3");

        ChildrenPageMenu.setBackground(new java.awt.Color(255, 255, 255));
        ChildrenPageMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 71, 155), 10));
        ChildrenPageMenu.setAutoscrolls(true);
        ChildrenPageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ChildrenPageMenu.setMaximumSize(new java.awt.Dimension(700, 400));
        ChildrenPageMenu.setMinimumSize(new java.awt.Dimension(700, 400));
        ChildrenPageMenu.setPreferredSize(new java.awt.Dimension(700, 400));
        ChildrenPageMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReturnBtnChild.setText("Go Back");
        ReturnBtnChild.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReturnBtnChild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnBtnChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnChildActionPerformed(evt);
            }
        });
        ChildrenPageMenu.add(ReturnBtnChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 20));

        numberLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numberLbl.setText("Name");
        numberLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChildrenPageMenu.add(numberLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 20));

        orphanLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        orphanLbl.setText("Orphan");
        orphanLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChildrenPageMenu.add(orphanLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 20));

        disabilityLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disabilityLbl.setText("Disability");
        disabilityLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChildrenPageMenu.add(disabilityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));

        disabilityTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChildrenPageMenu.add(disabilityTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 20));

        orphanCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        orphanCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        orphanCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orphanCbActionPerformed(evt);
            }
        });
        ChildrenPageMenu.add(orphanCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        nameTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChildrenPageMenu.add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 220, 20));

        addressLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressLbl.setText("Address");
        addressLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChildrenPageMenu.add(addressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 20));

        addressTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChildrenPageMenu.add(addressTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 20));

        clearBtnChild.setText("Clear Details");
        clearBtnChild.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBtnChild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtnChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnChildActionPerformed(evt);
            }
        });
        ChildrenPageMenu.add(clearBtnChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, 20));
        ChildrenPageMenu.add(socialLogoChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, -1));

        sponserChildLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/LogoSponsers.png"))); // NOI18N
        ChildrenPageMenu.add(sponserChildLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 110));

        mainChildLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/socialprotection.jpg"))); // NOI18N
        ChildrenPageMenu.add(mainChildLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 90));

        childrenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/childrenlogo.jpg"))); // NOI18N
        ChildrenPageMenu.add(childrenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 260, 240));

        getContentPane().add(ChildrenPageMenu, "card4");

        PensionPageMenu.setBackground(new java.awt.Color(255, 255, 255));
        PensionPageMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 71, 155), 10));
        PensionPageMenu.setAutoscrolls(true);
        PensionPageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PensionPageMenu.setMaximumSize(new java.awt.Dimension(700, 400));
        PensionPageMenu.setMinimumSize(new java.awt.Dimension(700, 400));
        PensionPageMenu.setName(""); // NOI18N
        PensionPageMenu.setPreferredSize(new java.awt.Dimension(700, 400));
        PensionPageMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prevemployLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prevemployLbl.setText("Previous Employment");
        prevemployLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PensionPageMenu.add(prevemployLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, 20));

        socialbenefitsLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        socialbenefitsLbl.setText("Social Benefits");
        socialbenefitsLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PensionPageMenu.add(socialbenefitsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 20));

        disabilitypenLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disabilitypenLbl.setText("Disability");
        disabilitypenLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PensionPageMenu.add(disabilitypenLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 20));

        prevemployTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        prevemployTf.setName(""); // NOI18N
        prevemployTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevemployTfActionPerformed(evt);
            }
        });
        PensionPageMenu.add(prevemployTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 20));

        socialbenefitsTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        socialbenefitsTf.setName(""); // NOI18N
        PensionPageMenu.add(socialbenefitsTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, 20));

        disabilitypenTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PensionPageMenu.add(disabilitypenTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, 20));

        returnBtnPension.setText("Go Back");
        returnBtnPension.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBtnPension.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtnPension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnPensionActionPerformed(evt);
            }
        });
        PensionPageMenu.add(returnBtnPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 20));

        clearBtnPen.setText("Clear Details");
        clearBtnPen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBtnPen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnPenActionPerformed(evt);
            }
        });
        PensionPageMenu.add(clearBtnPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, 20));
        PensionPageMenu.add(sponserLogoPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, -1));

        sponsersLogoPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/LogoSponsers.png"))); // NOI18N
        PensionPageMenu.add(sponsersLogoPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 110));

        mainLogoPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/socialprotection.jpg"))); // NOI18N
        PensionPageMenu.add(mainLogoPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 90));

        pensionerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WelfareAppFinal/pensionlogo.png"))); // NOI18N
        PensionPageMenu.add(pensionerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 240, 240));

        getContentPane().add(PensionPageMenu, "card5");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void houseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseComboBoxActionPerformed

    }//GEN-LAST:event_houseComboBoxActionPerformed

    private void returnBtnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnHouseActionPerformed
        // Code returning back to the main page and sets housing to false.
        WelfareAppPageMenu.setVisible(true);
        HousingPageMenu.setVisible(false);
    }//GEN-LAST:event_returnBtnHouseActionPerformed

    private void preferenceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenceTfActionPerformed

    }//GEN-LAST:event_preferenceTfActionPerformed

    private void clearBtnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnHouseActionPerformed
        // Clears details in the "Housing" class section.
        houseComboBox.setSelectedItem("");
        areaComboBox.setSelectedItem("");
        preferenceTf.setText("");

    }//GEN-LAST:event_clearBtnHouseActionPerformed

    private void ReturnBtnChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnChildActionPerformed
        // Code returning back to the main page and sets children to false.
        WelfareAppPageMenu.setVisible(true);
        ChildrenPageMenu.setVisible(false);
    }//GEN-LAST:event_ReturnBtnChildActionPerformed

    private void clearBtnChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnChildActionPerformed
        // Clears details in the "Children" class section.
        orphanCb.setSelectedItem("");
        nameTf.setText("");
        disabilityTf.setText("");
        addressTf.setText("");
    }//GEN-LAST:event_clearBtnChildActionPerformed

    private void returnBtnPensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnPensionActionPerformed
        // Code returning back to the main page and sets pension to false.
        WelfareAppPageMenu.setVisible(true);
        PensionPageMenu.setVisible(false);
    }//GEN-LAST:event_returnBtnPensionActionPerformed

    private void clearBtnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnPenActionPerformed
        // Clears details in the "Pension" class section.
        disabilitypenTf.setText("");
        prevemployTf.setText("");
        socialbenefitsTf.setText("");
    }//GEN-LAST:event_clearBtnPenActionPerformed

    private void prevemployTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevemployTfActionPerformed

    }//GEN-LAST:event_prevemployTfActionPerformed

    private void viewBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnMainActionPerformed
        /*
        Top Section Commented out for ArrayList Information to be linked.
        fname = fnameTb.getText();
        lname = lnameTb.getText();
        pAddress = pAddressTb.getText();
        cAddress = cAddressTb.getText();
        contactNum = contactNumTb.getText();
        
        //A new instance of P
        Welfare p = new Welfare();
        
        //Settting data memebers to be declared
        p.setFname(fname);
        p.setLname(lname);
        p.setpAddress(pAddress);
        p.setcAddress(cAddress);
        p.setPrevNum(contactNum);
         */
        //FILE OUTFILE
        //Members used to save the information required.
        // pps.txt created seperately to secure information.
        File ppsFile;
        FileWriter fw;
        BufferedWriter bw;
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        ppsNo = ppsTb.getText();

        //Information Input put through including catch IOExceptions. Also indluded "IF" statement for if no details given.
        try {
            ppsFile = new File("pps.txt");
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            fw = new FileWriter(ppsFile, true);
            bw = new BufferedWriter(fw);

            oStream.writeObject(aList);
            bw.write(ppsNo);
            bw.newLine();

            if (fnameTb.getText().equals("") || lnameTb.getText().equals("") || pAddressTb.getText().equals("")
                    || cAddressTb.getText().equals("") || contactNumTb.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "No viewed details.");
            } else if (count == 0) {
                JOptionPane.showMessageDialog(null, "There is no information to delete.");
            }else{
                JOptionPane.showMessageDialog(null, "Saved.");
               
                oStream.close();
                bw.close();
            }
        } catch (IOException z) {
            System.out.println(z);
        }
        
    }//GEN-LAST:event_viewBtnMainActionPerformed

    private void printActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionBtnActionPerformed

        /*
        Submit Button for Documents with Welfare App (File Writer and and Buffered Writer used to create new Welfare.txt)
        This has also been discovered and adjusted to open and run not only in Textpad but in other .exe related files.
         */
        //If Statments to procced to enter information.
        if (fnameTb.getText().equals("") || lnameTb.getText().equals("") || pAddressTb.getText().equals("")
                || cAddressTb.getText().equals("") || contactNumTb.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter all details to print.");
        } else if (count == 0) {
            JOptionPane.showMessageDialog(null, "There is no information to print.");
        } else {

            //FILE I/O Delcare Objects
            File outFile;
            FileWriter fw;
            BufferedWriter bw;

            //Gets text from declared variables stated on the top of this page.
            fname = fnameTb.getText();
            lname = lnameTb.getText();
            pAddress = pAddressTb.getText();
            cAddress = cAddressTb.getText();
            contactNum = contactNumTb.getText();
            try {
                outFile = new File("welfare.txt");
                fw = new FileWriter(outFile, true);
                bw = new BufferedWriter(fw);

                //File Writer displays a new line of data and then the string data gets sent ahead.
                bw.newLine();
                bw.write(fname);
                bw.newLine();
                bw.write(lname);
                bw.newLine();
                bw.write(pAddress);
                bw.newLine();
                bw.write(cAddress);
                bw.newLine();
                bw.write(contactNum);
                bw.newLine();
                //Close the Buffered Stream
                bw.close();

                //Code below prints out to given .exe file which must include stated .txt, .doc, etc
                ProcessBuilder pb = new ProcessBuilder("notepad.exe", "welfare.txt");
                pb.start();
                

                //Throws in catch Exceptions to locate any undeclared variables listed above with the letter E.
            } catch (IOException e) {
                System.out.println("Error Writing to File" + e);
            }
        }
    }//GEN-LAST:event_printActionBtnActionPerformed

    private void pensionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensionBtnActionPerformed

        // Switches Pension App page over JPanel Pension.
        HousingPageMenu.setVisible(false);
        WelfareAppPageMenu.setVisible(false);
        ChildrenPageMenu.setVisible(false);
        PensionPageMenu.setVisible(true);
    }//GEN-LAST:event_pensionBtnActionPerformed

    private void childBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childBtnActionPerformed

        // Switches Children App page over to JPanel Children
        HousingPageMenu.setVisible(false);
        WelfareAppPageMenu.setVisible(false);
        ChildrenPageMenu.setVisible(true);
        PensionPageMenu.setVisible(false);

    }//GEN-LAST:event_childBtnActionPerformed

    private void houseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseBtnActionPerformed

        // Switches Housing App page over to JPanel Housing
        HousingPageMenu.setVisible(true);
        WelfareAppPageMenu.setVisible(false);
        ChildrenPageMenu.setVisible(false);
        PensionPageMenu.setVisible(false);
    }//GEN-LAST:event_houseBtnActionPerformed

    private void addDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailsBtnActionPerformed

        /* ARRAY OF OBJECTS (Adding and Display)
        Adding a ArrayList to be stored. It then gets text from text fields and increments count.
        Gets Data Members ("ppsTb" hidden crossed out because of password field option on GUI).
         */
        ppsNo = ppsTb.getText();
        fname = fnameTb.getText();
        lname = lnameTb.getText();
        pAddress = pAddressTb.getText();
        cAddress = cAddressTb.getText();
        contactNum = contactNumTb.getText();

        Welfare a = new Welfare();
        a.setPpsNo(ppsNo);
        a.setFname(fname);
        a.setLname(lname);
        a.setpAddress(pAddress);
        a.setcAddress(cAddress);
        a.setContactNum(contactNum);
        

        /* 
        Adding a object to a Arraylist "aList" with the "add" method  listed below.
        Also inclued a empty field option to not proceed if the full information is not entered.
         */
        if (fnameTb.getText().equals("") || lnameTb.getText().equals("") || pAddressTb.getText().equals("")
                || cAddressTb.getText().equals("") || contactNumTb.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter all details to proceed.");
        } else {
            aList.add(a);
            JOptionPane.showMessageDialog(null, "Added.");

            //Increment of Counter on the Arraylist.
            count++;
        }
    }//GEN-LAST:event_addDetailsBtnActionPerformed

    private void contactNumTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumTbActionPerformed

    }//GEN-LAST:event_contactNumTbActionPerformed

    private void cAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddressTbActionPerformed

    }//GEN-LAST:event_cAddressTbActionPerformed

    private void pAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddressTbActionPerformed

    }//GEN-LAST:event_pAddressTbActionPerformed

    private void lnameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTbActionPerformed

    }//GEN-LAST:event_lnameTbActionPerformed

    private void fnameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTbActionPerformed

    }//GEN-LAST:event_fnameTbActionPerformed

    private void ppsTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppsTbActionPerformed

    }//GEN-LAST:event_ppsTbActionPerformed

    private void searchDetailsMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDetailsMainActionPerformed

        // Search Details of Welfare App
        //Entering and Requesting Searchtype.
        if (count == 0) {
            JOptionPane.showMessageDialog(null, "There is no information to search.");
        } else {
            String searchType = JOptionPane.showInputDialog(null, "Please enter Last Name provided for search details.");

            /*
            ARRAY OF OBJECTS (Adding Display and Search)
            Looping through to traverse through ArrayList "aList"
            For Each loop added with the letter delcared "n"
             */
            aList.stream().filter((n) -> (searchType.equalsIgnoreCase(n.getLname()))).forEachOrdered((n) -> {
                JOptionPane.showMessageDialog(null, "Contact: " + n.getContactNum() + "\n First Name: " + n.getFname() + "\n Last Name:  " + n.getLname() + "\n Prev Address: " + n.getpAddress() + "\n Current Address: " + n.getcAddress());
            });
        }
    }//GEN-LAST:event_searchDetailsMainActionPerformed

    private void saveBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnMainActionPerformed

        //FILE I/O (output.data)
        //File Outfile Tools used to view Output.data file
        File ppsFile;
        File inFile;
        FileReader fr;
        BufferedReader br;
        FileInputStream fStream;
        ObjectInputStream oStream;

        //Try and Catch elements included.
        try {
            ppsFile = new File("pps.txt");
            fr = new FileReader(ppsFile);
            br = new BufferedReader(fr);
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            ppsNo = br.readLine();

            /*Welfare x;
            x = (Welfare)oStream.readObject();
            Including applied ArrayList and then commenting out to connect to other pieces of code.
             */
            
            
            
            //Arraylist under Welfare delcared as xList.
            ArrayList<Welfare> xList;
            xList = (ArrayList<Welfare>) oStream.readObject();

            //If Statement to delcare if count is 0 then no info saved else proceed printing out and saving details.
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No info to view.");
                
            } else {
                xList.forEach((x) -> {
                    //Printing out the information to the screen.
                    JOptionPane.showMessageDialog(null, x.getFname() + "\n" + x.getLname() + "\n" + x.getpAddress() + "\n" + x.getcAddress() + "\n" + x.getContactNum() + "\n");
                });
                //Closing the Stream
                oStream.close();
                br.close();

                //Catch all Exceptions that include IOExceptions and Class Not Found Exceptions with the letter Z
            }
        } catch (IOException | ClassNotFoundException z) {
            System.out.println(z);
        }
        
        
        
    }//GEN-LAST:event_saveBtnMainActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        /* 
        ARRAY OF OBJECTS DELETING
        First If statement includes a condition for typing in all information and then else if gives a count.
        Code then proceeds to use the for loop that runs through each variable and then removes.
         */
        
        //If Statement included to not proceed without proper information given.
        if (fnameTb.getText().equals("") || lnameTb.getText().equals("") || pAddressTb.getText().equals("")
                || cAddressTb.getText().equals("") || contactNumTb.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter all details to delete.");

            //Else if with no information to delete
        } else if (count == 0) {
            JOptionPane.showMessageDialog(null, "There is no information to delete.");

            //Else proceed to run through Arraylist.
        } else {
            fname = fnameTb.getText();
            lname = lnameTb.getText();
            pAddress = pAddressTb.getText();
            cAddress = cAddressTb.getText();
            contactNum = contactNumTb.getText();
            
            //For each loop
            for (int i = 0; i < aList.size(); i++) {
                if (aList.get(i).getFname().equals(fname) && aList.get(i).getLname().equals(lname)
                        && aList.get(i).getpAddress().equals(pAddress) && aList.get(i).getcAddress().equals(cAddress)
                        && aList.get(i).getContactNum().equals(contactNum)) {
                    
                    //Removing of aList files on the screen.
                    aList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null, "Deleted.");
                    ppsTb.setText("");
                    fnameTb.setText("");
                    lnameTb.setText("");
                    pAddressTb.setText("");
                    cAddressTb.setText("");
                    contactNumTb.setText("");
                    break;

                }
                if (i == count - 1) {
                    JOptionPane.showMessageDialog(null, "Details not found.");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ppsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppsCheckBoxActionPerformed

        // Hiiden Password with "Echo Char" Function included. A option to toggle on and off the visiblity of a password.
        if (ppsCheckBox.isSelected()) {
            ppsTb.setEchoChar((char) 0);
        } else {
            ppsTb.setText("*********");
        }
    }//GEN-LAST:event_ppsCheckBoxActionPerformed

    private void ppsTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppsTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 40:
                fnameTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_ppsTbKeyPressed

    private void fnameTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 40:
                lnameTb.requestFocus();
                break;

            case 38:
                ppsTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_fnameTbKeyPressed

    private void pAddressTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pAddressTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 38:
                lnameTb.requestFocus();
                break;

            case 40:
                cAddressTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_pAddressTbKeyPressed

    private void lnameTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 38:
                fnameTb.requestFocus();
                break;

            case 40:
                pAddressTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_lnameTbKeyPressed

    private void cAddressTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cAddressTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 38:
                pAddressTb.requestFocus();
                break;

            case 40:
                contactNumTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_cAddressTbKeyPressed

    private void contactNumTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumTbKeyPressed

        // Up and Down on Arrow Keys ".getKeyCode"... Number corresponds to layout of keyboard.
        switch (evt.getKeyCode()) {
            case 38:
                cAddressTb.requestFocus();
                break;
        }
    }//GEN-LAST:event_contactNumTbKeyPressed

    private void orphanCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orphanCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orphanCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelfareAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WelfareAppGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChildrenPageMenu;
    private javax.swing.JLabel HomelessLogo;
    private javax.swing.JPanel HousingPageMenu;
    private javax.swing.JPanel PensionPageMenu;
    private javax.swing.JToggleButton ReturnBtnChild;
    private javax.swing.JPanel WelfareAppPageMenu;
    private javax.swing.JButton addDetailsBtn;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTf;
    private javax.swing.JComboBox<String> areaComboBox;
    private javax.swing.JLabel areaLbl;
    private javax.swing.JTextField cAddressTb;
    private javax.swing.JLabel caddressLbl;
    private javax.swing.JToggleButton childBtn;
    private javax.swing.JLabel childrenLogo;
    private javax.swing.JButton clearBtnChild;
    private javax.swing.JButton clearBtnHouse;
    private javax.swing.JButton clearBtnPen;
    private javax.swing.JLabel contactNumLbl;
    private javax.swing.JTextField contactNumTb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel disabilityLbl;
    private javax.swing.JTextField disabilityTf;
    private javax.swing.JLabel disabilitypenLbl;
    private javax.swing.JTextField disabilitypenTf;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JTextField fnameTb;
    private javax.swing.JToggleButton houseBtn;
    private javax.swing.JComboBox<String> houseComboBox;
    private javax.swing.JLabel housetypeLbl;
    private javax.swing.JLabel housingLogo;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTb;
    private javax.swing.JLabel mainChildLogo;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel mainLogoPen;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel ncirlLogo;
    private javax.swing.JLabel numberLbl;
    private javax.swing.JComboBox<String> orphanCb;
    private javax.swing.JLabel orphanLbl;
    private javax.swing.JTextField pAddressTb;
    private javax.swing.JLabel paddressLbl;
    private javax.swing.JToggleButton pensionBtn;
    private javax.swing.JLabel pensionerLogo;
    private javax.swing.JCheckBox ppsCheckBox;
    private javax.swing.JLabel ppsLbl;
    private javax.swing.JPasswordField ppsTb;
    private javax.swing.JTextField preferenceTf;
    private javax.swing.JLabel prefernceLbl;
    private javax.swing.JLabel prevemployLbl;
    private javax.swing.JTextField prevemployTf;
    private javax.swing.JButton printActionBtn;
    private javax.swing.JToggleButton returnBtnHouse;
    private javax.swing.JToggleButton returnBtnPension;
    private javax.swing.JButton saveBtnMain;
    private javax.swing.JButton searchDetailsMain;
    private javax.swing.JLabel socialLogoChild;
    private javax.swing.JLabel socialLogoHouse;
    private javax.swing.JLabel socialbenefitsLbl;
    private javax.swing.JTextField socialbenefitsTf;
    private javax.swing.JLabel sponserChildLogo;
    private javax.swing.JLabel sponserLogoPen;
    private javax.swing.JLabel sponsersLogoMain;
    private javax.swing.JLabel sponsersLogoMain2;
    private javax.swing.JLabel sponsersLogoPen;
    private javax.swing.JButton viewBtnMain;
    // End of variables declaration//GEN-END:variables
}
